### ISSUE TITLE
json deserialization invoked too many times

### ISSUE THREAD

**Issue by candrys** [configcat/.net-sdk#22]
Hi, 
One of our use cases is getting all enabled features for user. During development we've noticed that every method [ConfigCatClient](https://github.com/configcat/.net-sdk/blob/master/src/ConfigCatClient/ConfigCatClient.cs) class is directly or indirectly deserializing settings json file, which is causing some performance issues. Was this intended behavior or do you think it could be changed that deserialization happens once after file is refreshed.

**Comment by endret** [comment]
Hi @candrys,

Thank you for the report, you are right our solution deserializes the config file 'all' times. Can you explain how do you use the configcat, its help to us understand why do you have any performance issues?
Have you use the client with any custom caching solution?

Thanks,
Endre

**Comment by pawmil** [comment]
Hi @endret 

@candrys is on vacation till the end of the week so I will answer your question. We are in the process of migrating from the previous feature toggle provider to configcat. For the old feature toggle provider we used the approach that the frontend part of our applications asked backend for the names of all enabled feature toggles. We may change it in the future but as the first step of the migration, we decided to use the same approach (to simplify it). That's why on the backend side we need to check all feature toggles and their values and it causes performance issues.
I saw that you already created a pull request correcting the issue. I can't wait to use the new version :) 

Thanks,
Pawel

**Comment by endret** [comment]
Hi @pawmil ,

Thank you for the detailed answer, we are really happy to choose us, can I ask what was your previous feature toggle provider and why did you make a decision to change it?

We released the new version of .net sdk you can update it (https://github.com/configcat/.net-sdk/releases/tag/v6.2.1).

If you are satisfied with ConfigCat, please help us grow by leaving a review (https://www.trustradius.com/welcome/configcat).

Thanks,
Endre

**Comment by endret** [comment]
fixed in #24
